FROM node:20-alpine AS build

WORKDIR /app

COPY package.json package-lock.json ./

RUN npm install

COPY . .

EXPOSE 4173

ARG PORT 

ENV PORT=$PORT

RUN npm run build

CMD ["npm","run","preview","--","--host"]